apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /api
          backend:
            serviceName: api
            servicePort: 8000
        - path: /Dashboard
          backend:
            serviceName: Dashboard
            servicePort: 9000