apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-saleor-ingress
spec:
  rules:
  - http:
      paths:
        - path: 
          backend:
            serviceName: api
            servicePort: 8000
        - path: 
          backend:
            serviceName: Dashboard
            servicePort: 9000