name: Build image and push

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR }}
          username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }} 
          
          
      - name: Build docker image and push to AC
        run: |
            docker compose build 
            docker images
            docker tag workflow-pipeline_dashboard ${{ secrets.ACR }}/dashboard
            docker tag workflow-pipeline_api ${{ secrets.ACR }}/api
            docker push ${{ secrets.ACR }}/dashboard
            docker push ${{ secrets.ACR }}/api

            

      
          
