name: Build image and push

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: ACR creation if doesnt exist
        run: |
          az acr create --resource-group ${{ secrets.RG_NAME }} --name ${{ secrets.ACR_NAME }} --sku Basic

      - name: ACR login
        run: |
          docker login bstsreg.azurecr.io --username c93af96d-c7f3-4294-81e6-c2bafd7afc80 --password dBK-bXLW9gfuAuCmsszEW0c-XBRj5OhSwn  
      
          
# #       - uses: azure/docker-login@v1
#         with:
#           login-server: ${{ secrets.ACR }}
#           username: ${{ secrets.ACR_username }}
#           password: ${{ secrets.ACR_password }} 
          
          
      - name: Build docker image and push to AC
        run: |
            docker compose build 
            docker images
            docker tag workflow-pipeline_dashboard ${{ secrets.ACR }}/dashboard
            docker tag workflow-pipeline_api ${{ secrets.ACR }}/api
            docker push ${{ secrets.ACR }}/dashboard
            docker push ${{ secrets.ACR }}/api

            

      
          
